version: '3.8'
services:
  db:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:password@db:5432/test
      RAILS_ENV: development
    ports:
      - "3000:3000"
    depends_on:
      - db
